name: Playwright Login Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-login:
    # El job se ejecuta dentro del contenedor oficial de Playwright (incluye navegadores y deps)
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.2-noble  # <- REEMPLAZA con la versión que coincida con la de tu repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js (inside container)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # NO ejecutar `npx playwright install --with-deps` ni usar microsoft/playwright-github-action
      # porque el contenedor ya trae las dependencias del sistema y los navegadores

      - name: Run Playwright tests
        run: pnpm exec playwright test --reporter=list
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          # añade aquí cualquier secret más que uses (KINDE_* etc.)

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
